export const ACTIONCODE = {
  COMMON001: '地址栏已写入sessionid,sessionid为：',
  COMMON002: '地址栏没有写入sessionid，即将从终端获取...',
  COMMON003: '从终端获取到sessionid,sessionid为：',
  COMMON004: '不能从终端获取到sessionid',
  COMMON005: '获取到的sessionid与本地存储的相同，读取缓存login信息、头像，获取到的sessionid与缓存sessionid分别为：',
  COMMON006: '获取到的ID与本地不同，即将发送新的login请求，并且将session storage中isLoadingStorage置为false，isLogin置为no，sessionid置为新取得的sessionid',
  COMMON007: '没有传入sessionid参数，不能发送login请求',
  COMMON008: 'session storage已保存userinfo，从session storage取userinfo，并且渲染用户信息、根据crmID获取头像,用户信息：',
  COMMON009: 'login请求响应超时，isLogin改为no',
  COMMON010: 'login请求响应成功，返回结果：',
  COMMON011: 'login请求响应失败，responseText： ',
  COMMON012: '渲染用户信息(除头像)',
  COMMON013: '本地已经保存用户头像，不再发送请求获取用户头像',
  COMMON014: '获取用户头像getUserHeadPortraitByCRMId超时',
  COMMON015: '获取用户头像成功',
  COMMON016: '获取用户头像失败，错误信息： ',
  COMMON017: '移除缓存中isLogin,sessionid,userinfo',
  COMMON018: '不能识别终端方法，可能在浏览器环境中',
  COMMON019: '不能从终端获取sessonid',
  COMMON020: '从终端获取到sessonid： ',
  COMMON021: '终端功能点日志参数： ',
  COMMON022: '即将同步获取报名和收藏状态...',
  COMMON023: '获取报名和收藏状态超时',
  COMMON024: '获取报名和收藏状态成功',
  COMMON025: '获取报名和收藏状态失败，错误码： ',
  COMMON026: 'documentType和documentId分别为： ',
  COMMON027: '获取文档超时',
  COMMON028: '获取文档成功',
  COMMON029: '获取文档错误，错误码： ',
  COMMON030: '从缓存中渲染合作伙伴',
  COMMON031: 'getPartners响应超时',
  COMMON032: 'getPartners成功',
  COMMON033: 'getPartners错误，错误码： ',
  COMMON034: '已经报过名',
  COMMON035: '参会人数已满',
  COMMON036: '即将发送报名请求...',
  COMMON037: 'signupMeeting超时',
  COMMON038: 'signupMeeting成功',
  COMMON039: 'signupMeeting失败，错误码： ',
  COMMON040: '即将发送signinMeeting请求',
  COMMON041: 'signinMeeting超时',
  COMMON042: 'signinMeeting成功',
  COMMON043: 'signinMeeting失败',
  COMMON044: '即将发送bookmarkMeeting请求...',
  COMMON045: 'bookmarkMeeting超时',
  COMMON046: '取消收藏成功',
  COMMON047: '收藏会议成功',
  COMMON048: 'bookmarkMeeting失败，错误码： ',
  COMMON049: '这是IE浏览器',
  COMMON050: 'serverinfo已经保存在缓存，返回缓存中的serverinfo',
  COMMON051: '从本地sessionStorage中提取serverinfo: ',
  COMMON052: '正在从终端获取serverinfo...',
  COMMON053: '没取到serverinfo,再取一次...',
  COMMON054: '替换serverName: ',
  COMMON055: '从终端查到serveName为null，无法替换，返回',
  COMMON056: '从PHP中解析地址的函数接收到url： ',
  COMMON057: 'PHP页面url的serverName： ',
  COMMON058: 'PHP页面url的host不是IP地址，是个serverinfo，那么替换为相应的IP，host为： ',
  COMMON059: '替换后的PHP页面URL为： ',
  COMMON060: 'PHP页面url的host是IP地址，可以直接使用',
  COMMON061: '被使用的PHP页面的url为',
  COMMON062: 'ajax访问PHP页面超时',
  COMMON063: 'PHP页面获取成功',
  COMMON064: 'wav格式文件从PHP页面解析完成！解析后数据：',
  COMMON065: '非wav格式文件从PHP页面解析完成！解析后数据： ',
  COMMON066: '音频播放地址： ',
  COMMON067: 'PHP页面获取失败',
  COMMON068: '最终播放地址： ',
  COMMON069: 'isLogin为yes，从缓存中取个人信息： ',
  COMMON070: 'isLogin为yes，从缓存中取sessionid： ',
  INDEX001: '点击了立即报名按钮',
  INDEX002: '开始发送报名请求',
  INDEX003: '点击了收藏按钮',
  INDEX004: '会议id及收藏状态： ',
  INDEX005: '即将开始获取最新会议列表： ',
  INDEX006: '获取最新会议列表超时： ',
  INDEX007: '获取最新会议列表成功 ',
  INDEX008: '获取最新会议列表失败 ',
  HISTORY001: '即将开始获取历史会议列表',
  HISTORY002: '获取历史会议列表成功',
  HISTORY003: '获取历史会议列表失败',
  CONFINFO01: '即将获取会议资讯列表',
  CONFINFO02: '获取会议资讯列表超时',
  CONFINFO03: '获取会议资讯列表失败',
  PER001: '速记url: ',
  PER002: '即将开始获取我的公开会议列表',
  PER003: '获取公开会议列表超时',
  PER004: '获取公开会议列表成功，但不渲染页面',
  PER005: '公开会议列表获取成功，处理后开始渲染页面',
  PER006: '公开会议列表获取失败，错误码： ',
  PER007: '即将开始获取私人会议列表',
  PER008: '获取私人会议列表超时',
  PER009: '获取私人会议列表成功，但不渲染页面',
  PER010: '获取私人会议列表成功，处理数据后开始渲染页面',
  PER011: '获取私人会议列表失败：',
  MEETINGDETAIL001: '会议状态不为STARTED，return false',
  MEETINGDETAIL002: '有报名权力',
  MEETINGDETAIL003: '已经报过名',
  MEETINGDETAIL004: '这是电话会议，弹窗结束',
  MEETINGDETAIL005: '获取视频直播ownerid: ',
  MEETINGDETAIL006: '已经获得视频直播ownerid,禁止重复获取',
  MEETINGDETAIL007: '开始获取音频流...音频流地址为：',
  MEETINGDETAIL008: '已经获得音频流地址，禁止重复获取, 地址为：',
  MEETINGDETAIL009: '没有报过名，即将报名...',
  MEETINGDETAIL010: '获取视频直播ownerid',
  MEETINGDETAIL011: '已经获得视频直播ownerid,禁止重复获取：',
  MEETINGDETAIL012: '开始获取音频流...音频流地址为：',
  MEETINGDETAIL013: '看速记',
  MEETINGDETAIL014: '获取视频直播ownerid',
  MEETINGDETAIL015: '已经获得视频直播ownerid,禁止重复获取：',
  MEETINGDETAIL016: '点击了下载附件',
  MEETINGDETAIL017: 'replyId',
  MEETINGDETAIL018: '即将发送评论',
  MEETINGDETAIL019: '发送评论超时',
  MEETINGDETAIL020: '发送评论成功',
  MEETINGDETAIL021: '发送评论失败',
  MEETINGDETAIL022: '即将发送获取评论数据请求',
  MEETINGDETAIL023: '获取评论数据超时',
  MEETINGDETAIL024: '评论数据请求完成',
  MEETINGDETAIL025: '评论数据请求错误，错误码：',
  MEETINGDETAIL026: '即将开始获取会议详情内容',
  MEETINGDETAIL027: '根据会议id请求数据，请求成功，处理数据后开始渲染页面',
  MEETINGDETAIL028: '会议状态：',
  MEETINGDETAIL029: '根据会议id请求数据，请求错误，错误码：',
  MEETINGDETAIL030: '正在获取直播流...',
  MEETINGDETAIL031: '音频直播流获取成功：',
  MEETINGDETAIL032: '获取音频直播流失败：',
  MEETINGDETAIL033: '会议状态不是STARTED或ENDED，return false',
  MEETINGDETAIL034: '播放器即将播放的地址为： ',
  MEETINGDETAIL035: '音频播放器开始播放',
  MEETINGDETAIL036: '重新载入播放器完成',
  MEETINGDETAIL037: '没有传入meetingID或broadcastType！return！',
  MEETINGDETAIL038: '会议状态不是已开始或已结束，return false！',
  MEETINGDETAIL039: 'ownerId获取成功: ',
  MEETINGDETAIL040: 'ownerId获取失败',
  MEETINGDETAIL041: 'showVideo函数中没有传入videoCode或者meetingStatus，return',
  MEETINGDETAIL042: '获得视频直播ownerid，并开始创建播放器',
  MEETINGDETAIL043: 'load播放器tag...',
  MEETINGDETAIL044: '读取vod标签',
  MEETINGDETAIL045: '读取live标签',
  MEETINGDETAIL046: '读取doc标签',
  MEETINGDETAIL047: '播放器即将播放的地址为： ',
  MEETINGDETAIL048: '会议ID为：',
  SEARCH001: '看速记: ',
  SEARCH002: '搜索会议请求超时',
  SEARCH003: '搜索会议列表获取成功',
  SETCONF001: '获取联系人列表超时',
  SETCONF002: '获得联系人数据成功',
  SETCONF003: '获取联系人列表超时',
  SETCONF004: '初始化左侧好友列表',
  SETCONF005: '创建会议请求超时',
  SETCONF006: '创建会议成功',
  SETCONF007: '创建会议请求失败',
  SETCONF008: '联系人操作: ',
  SETCONF009: '联系人操作超时 ',
  SETCONF010: '联系人操作成功 ',
  SETCONF011: '联系人操作失败 '
}
